timezone: Europe/Berlin

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

url: https://www.dhiller.dev
enforce_ssl: www.dhiller.dev

collections:
  jobs:
    output: false
  articles:
    output: false
  navigation:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
