timezone: Europe/Berlin

url: https://www.dhiller.de
enforce_ssl: www.dhiller.de

collections:
  jobs:
    output: false
  articles:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
